name: terraform-deploy

on:
  push:
    branches:
      - main
    paths:
      - "infrastructure/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  TF_IN_AUTOMATION: true
  TF_WORKING_DIR: infrastructure

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.TF_WORKING_DIR }}/.terraform
            ~/.terraform.d/plugin-cache
          key: tf-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            tf-${{ runner.os }}-

      - name: Write terraform.tfvars
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          cat > terraform.tfvars <<'EOF'
          aws_region                          = "us-east-1"
          profile_picture_bucket_name         = "dexbooru-prd-pfps"
          post_picture_bucket_name            = "dexbooru-prd-posts"
          post_collection_picture_bucket_name = "dexbooru-prd-collections"
          dexbooru_webapp_iam_user_name       = "dexbooru-webapp-iam-user"
          dexbooru_webapp_policy_name         = "dexbooru-webapp-policy"
          cdn_domain                          = "cdn.neetbyte.fun"
          cdn_zone_name                       = "neetbyte.fun"
          EOF

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false -backend-config=backend.tfbackend -reconfigure

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve tfplan
